In [2]:
import cv2
import dlib
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import array_to_img

In [3]:

model = tf.keras.models.load_model('shaq-facial-CNN')

In [8]:
# Initialize the Dlib face detector and shape predictor
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")

preprocessed_faces = []


def align_and_crop_faces(image_path, padding=50):
    # Convert the image to grayscale for face detection
    
    image = cv2.imread(image_path)
    
    gray = image
    
    # Detect faces in the image
    faces = detector(gray)

    # Check if a face is detected
    if len(faces) > 0:
        # Assume there's only one face in the image for simplicity
        face = faces[0]

        # Get the facial landmarks for face alignment
        shape = predictor(gray, face)

        # Define the coordinates for the eyes
        left_eye = shape.part(36)  # Left eye
        right_eye = shape.part(45)  # Right eye

        # Calculate the angle for rotation (to make eyes horizontal)
        angle = np.arctan2(right_eye.y - left_eye.y, right_eye.x - left_eye.x)
        angle = np.degrees(angle)

        # Calculate new coordinates for cropping without padding
        x = max(0, face.left() - padding)
        y = max(0, face.top() - padding)
        w = min(image.shape[1], face.right() + padding) - x
        h = min(image.shape[0], face.bottom() + padding) - y

        # Crop the image with the new coordinates
        cropped_face = image[y:y+h, x:x+w]

        # Check if the cropped face is not empty
        if not cropped_face.size == 0:
            preprocessed_faces.append(cropped_face)

In [14]:
align_and_crop_faces('shaq4.jpg')

for face in preprocessed_faces:
    
    img = keras.preprocessing.image.load_img(
            "shaq4.jpg", target_size=(256, 256))

    img_array = keras.preprocessing.image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)

    predictions = model.predict(img_array)

    print('\n')
    print(predictions)
    print('\n')

1/1 [==============================] - 0s 116ms/step


[[2.160138e-15 1.000000e+00]]


1/1 [==============================] - 0s 117ms/step


[[2.160138e-15 1.000000e+00]]


1/1 [==============================] - 0s 116ms/step


[[2.160138e-15 1.000000e+00]]


1/1 [==============================] - 0s 117ms/step


[[2.160138e-15 1.000000e+00]]


1/1 [==============================] - 0s 117ms/step


[[2.160138e-15 1.000000e+00]]


